### ISSUE TITLE
Generator fails when connectionstring contains curly braces

### ISSUE THREAD

**Issue by Spongeroberto** [loresoft/EntityFrameworkCore.Generator#28]
I had a connectionstring with a password with curly braces, for example:

> connectionSTring: 'Data Source=host;Initial Catalog=database; User ID=username;Password=pass}'

Executing the tool results in the following stacktrace:

`12:21:43 I Loading options file: generation.yml
12:21:43 I Loading database model ...
12:21:43 F Host terminated unexpectedly
System.FormatException: One of the identified items was in an invalid format.
   at EntityFrameworkCore.Generator.VariableDictionary.Eval(String variableOrText, ISet`1 loop) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\VariableDictionary.cs:line 182
   at EntityFrameworkCore.Generator.VariableDictionary.Get(String name) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\VariableDictionary.cs:line 62
   at EntityFrameworkCore.Generator.CodeGenerator.ResolveConnectionString(DatabaseOptions database) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\CodeGenerator.cs:line 258
   at EntityFrameworkCore.Generator.CodeGenerator.GetDatabaseModel(IDatabaseModelFactory factory) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\CodeGenerator.cs:line 248
   at EntityFrameworkCore.Generator.CodeGenerator.Generate(GeneratorOptions options) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\CodeGenerator.cs:line 41
   at EntityFrameworkCore.Generator.GenerateCommand.OnExecute(CommandLineApplication application) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator\GenerateCommand.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass142_0.<OnExecute>b__0()
   at EntityFrameworkCore.Generator.Program.Main(String[] args) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator\Program.cs:line 50`

The problem is solved by changing the curly brace to a double curly brace.

**Comment by hamedsabzian** [comment]
you must replace single "}" with "}}".
there is some special characters like this:
:, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @

**Comment by pwelter34** [comment]
Fixed in v6.2
