### ISSUE TITLE
bug: null exception when have generation.yml file

### ISSUE THREAD

**Issue by giangcoi48k** [loresoft/EntityFrameworkCore.Generator#54]
I used `efg initialize -c <ConnectionString>` to generated generation.yml file.
Then run `efg generate -c <ConnectionString>`
It always throw exception:
```C#
 F Host terminated unexpectedly
System.NullReferenceException: Object reference not set to an instance of an object.
   at EntityFrameworkCore.Generator.ModelGenerator.IsIgnored[TOption](Entity entity, TOption options, SharedModelOptions sharedOptions) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\ModelGenerator.cs:line 616
   at EntityFrameworkCore.Generator.ModelGenerator.CreateModel[TOption](Entity entity, TOption options, ModelType modelType) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\ModelGenerator.cs:line 409
   at EntityFrameworkCore.Generator.ModelGenerator.GetModels(Entity entity) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\ModelGenerator.cs:line 383
   at EntityFrameworkCore.Generator.ModelGenerator.Generate(GeneratorOptions options, DatabaseModel databaseModel, IRelationalTypeMappingSource typeMappingSource) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\ModelGenerator.cs:line 70
   at EntityFrameworkCore.Generator.CodeGenerator.Generate(GeneratorOptions options) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\CodeGenerator.cs:line 47
   at EntityFrameworkCore.Generator.GenerateCommand.OnExecute(CommandLineApplication application) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator\GenerateCommand.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at EntityFrameworkCore.Generator.Program.Main(String[] args) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator\Program.cs:line 50
```
Without generation.yml, it work normaly

**Comment by BartBr** [comment]
try putting all empty options in comments
example:
#tables: 
#schemas:

**Comment by pwelter34** [comment]
if you're willing to share your yml file, then i can debug the issue.

**Comment by BartBr** [comment]
Did some more research on the bugs.
You can solve it by changing commenting 3 lines in generation.yml
However, it should be solved by allowing those 3 lines to be empty

I found 3 properties that can't be empty
1/ model.shared.include
2/ model.shared.exclude
3/ scripts

quick-fix it by commenting the following lines (#):
```
model:
  shared:
    namespace: '{Project.Namespace}.Domain.Models'
    directory: '{Project.Directory}\Domain\Models'
    #include: 
    #exclude: 
...
#script: 
```

Bug 1:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EntityFrameworkCore.Generator.ModelGenerator.IsIgnored[TOption](Entity entity, TOption options, SharedModelOptions sharedOptions) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\ModelGenerator.cs:line 616
```

Bug 2: 
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EntityFrameworkCore.Generator.ModelGenerator.IsIgnored[TOption](Entity entity, TOption options, SharedModelOptions sharedOptions) in C:\projects\entityframeworkcore-generator\src\EntityFrameworkCore.Generator.Core\ModelGenerator.cs:line 618

```
Bug 3: empty scripts results in:
`System.NullReferenceException: Object reference not set to an instance of an object. at EntityFrameworkCore.Generator.CodeGenerator.GenerateContextScriptTemplates(EntityContext entityContext) in C:\projects\entityframeworkcoreenerator\src\EntityFrameworkCore.Generator.Core\CodeGenerator.cs:line 329`

generation.yml that produces the 3 bugs:
```
project:
  namespace: '{Database.Name}'
  directory: .\
database:
  name: 
  provider: SqlServer
  connectionString: 'ACorrectConnectionString'
  connectionName: ConnectionStrings:Generator
  userSecretsId: 4b8887f1-6555-455a-b717-1abbe8656e9a
  tableNaming: Singular
  tables: 
  schemas: 
data:
  context:
    name: '{Database.Name}Context'
    baseClass: DbContext
    propertyNaming: Plural
    namespace: '{Project.Namespace}.Data'
    directory: '{Project.Directory}\Data'
    document: false
  entity:
    baseClass: 
    entityNaming: Singular
    relationshipNaming: Plural
    prefixWithSchemaName: false
    namespace: '{Project.Namespace}.Data.Entities'
    directory: '{Project.Directory}\Data\Entities'
    document: false
  mapping:
    namespace: '{Project.Namespace}.Data.Mapping'
    directory: '{Project.Directory}\Data\Mapping'
    document: false
  query:
    generate: true
    indexPrefix: By
    uniquePrefix: GetBy
    namespace: '{Project.Namespace}.Data.Queries'
    directory: '{Project.Directory}\Data\Queries'
    document: false
model:
  shared:
    namespace: '{Project.Namespace}.Domain.Models'
    directory: '{Project.Directory}\Domain\Models'
    include: 
    exclude: 
  read:
    generate: true
    name: '{Entity.Name}ReadModel'
    baseClass: 
    include: 
    exclude: 
    namespace: 
    directory: 
    document: false
  create:
    generate: true
    name: '{Entity.Name}CreateModel'
    baseClass: 
    include: 
    exclude: 
    namespace: 
    directory: 
    document: false
  update:
    generate: true
    name: '{Entity.Name}UpdateModel'
    baseClass: 
    include: 
    exclude: 
    namespace: 
    directory: 
    document: false
  mapper:
    generate: true
    name: '{Entity.Name}Profile'
    baseClass: AutoMapper.Profile
    namespace: '{Project.Namespace}.Domain.Mapping'
    directory: '{Project.Directory}\Domain\Mapping'
    document: false
  validator:
    generate: true
    name: '{Model.Name}Validator'
    baseClass: AbstractValidator<{Model.Name}>
    namespace: '{Project.Namespace}.Domain.Validation'
    directory: '{Project.Directory}\Domain\Validation'
    document: false
script: 
```

**Comment by pwelter34** [comment]
Thanks for reporting and the help.  Version 2.5.0.121 should resolve the issues.
